#!/bin/bash
#SBATCH -A coreai_mlperf_training              # slurm account
#SBATCH -p b200-a01r            # slurm partition name
#SBATCH -N 1                    # number of nodes
#SBATCH -t 00:30:00             # wall time
#SBATCH -J "coreai_mlperf_training-flux.test"         # job name
#SBATCH --exclusive             # exclusive node access
#SBATCH --mem=0                 # all mem avail
#SBATCH --ntasks-per-node=1     # n tasks per machine (one task per gpu)
#SBATCH --overcommit
#SBATCH --dependency=singleton  # only run one instance at a time
#SBATCH --constraint=b200  # only run one instance at a time

# Run command:
# sbatch -N 1 --ntasks-per-node=8 -t 00:20:00 run.sub

set -eux

CONTAINER=ghcr.io/nvidia/jax:maxtext-2025-07-18
# CONTAINER=gitlab-master.nvidia.com/haixinl/container_repo/midjourney:2025-4-21-nccl-227
# CONTAINER=gitlab-master.nvidia.com/haixinl/container_repo/maxdiffusion:jax-2025_3_20-nvls-fix-nccl-227-maxunrollfactor8
# CONTAINER=gitlab-master.nvidia.com/abgoel/paxml-containers:haiku-nightly-04-15-25-nccl-ub-reg

BASE_WORKSPACE_DIR="/lustre/fsw/coreai_mlperf_training/users/haixinl/maxtext" ## location to write logs and checkpoints to
WORKSPACE_DIR=/opt/workspace

BASE_CODE_DIR="/lustre/fsw/coreai_mlperf_training/users/haixinl/my_code/maxtext"
CODE_DIR=/opt/maxtext

MOUNTS="--container-mounts=$BASE_WORKSPACE_DIR:$WORKSPACE_DIR,$BASE_CODE_DIR:$CODE_DIR"

EXPORTS="--export=ALL"

export BASE_SCRIPT="$CODE_DIR/run_single_llama3_70b.sh"

# Get the current timestamp
TIMESTAMP=$(date +"%Y%m%d%H%M%S")
# Append the timestamp to EXPT_ID
EXPT_ID="${SLURM_JOB_ID}_${TIMESTAMP}"

OUTPUT_DIR="${BASE_WORKSPACE_DIR}/outputs/${EXPT_ID}"
mkdir -p ${OUTPUT_DIR}
OUTFILE="${OUTPUT_DIR}/output-%j-%n-%t.txt"

LOG_DIR_LOCAL="${WORKSPACE_DIR}/outputs/${EXPT_ID}"

cmd="$(cat <<EOF
echo "*******STARTING********"
cd ${CODE_DIR}
nvidia-smi
LOG_DIR=${LOG_DIR_LOCAL} CODE_DIR=${CODE_DIR} bash $BASE_SCRIPT
EOF
)"

echo $cmd
srun -o $OUTFILE -e $OUTFILE --container-image="$CONTAINER" $MOUNTS $EXPORTS bash -e -c "${cmd}"
set +x

